n1 = float(input("Digite a primeira nota:"))
print("-"*20)
n2 = float(input("Digite a segunda nota:"))
print("-"*20)
n3 = float(input("Digite a terceira nota:"))
print("-"*20)
n4 = float(input("Digite a quarta nota:"))
print("-"*20)
print("A media do aluno é:{}".format((n1+n2+n3+n4)/4))
print("-"*20)