print("-"*20)
n1 = float(input("Digite um lado do quadrado:"))
print("-"*20)
print("A área do quadrado é {}".format(n1*n1))
print("-"*20)
print("e o dobro desta área é {}".format((n1*n1)*2))
print("-"*20)